# Generated by Django 2.2.1 on 2019-05-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detective_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FredStatisticCategory',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('parent_id', models.IntegerField()),
                ('notes', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='stocks',
            name='listing',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='stocks',
            name='market_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stocks',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='stocks',
            unique_together={('code', 'name', 'listing')},
        ),
        migrations.CreateModel(
            name='USStocks',
            fields=[
                ('cik', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('security', models.TextField()),
                ('security_wiki_link', models.URLField(null=True)),
                ('ticker', models.CharField(default='', max_length=20)),
                ('ticker_symbol_link', models.URLField(null=True)),
                ('category_code', models.CharField(max_length=20, null=True)),
                ('category_name', models.TextField()),
                ('category_detail', models.TextField()),
                ('sec_filing', models.URLField()),
                ('issued_shares', models.FloatField(null=True)),
                ('capital', models.FloatField(null=True)),
                ('par_value', models.IntegerField(null=True)),
                ('curr', models.CharField(max_length=3, null=True)),
                ('tel', models.CharField(max_length=20, null=True)),
                ('address', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('location_link', models.URLField(null=True)),
                ('date_first_added', models.DateField(null=True)),
                ('listing', models.CharField(default='Y', max_length=1)),
                ('founded', models.TextField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('cik', 'security')},
            },
        ),
        migrations.CreateModel(
            name='TargetStocks',
            fields=[
                ('valuation_date', models.CharField(default='2019-05-07', max_length=10)),
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField()),
                ('curr', models.CharField(max_length=3)),
                ('last_price', models.FloatField(null=True)),
                ('target_price', models.FloatField(null=True)),
                ('target_price2', models.FloatField(null=True)),
                ('ratio', models.FloatField(null=True)),
                ('valuation', models.CharField(default='B', max_length=1)),
                ('permanence', models.CharField(default='B', max_length=1)),
                ('audit', models.CharField(default='B', max_length=1)),
                ('required_yield', models.FloatField(null=True)),
                ('return_on_equity', models.FloatField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plus_npv', models.CharField(default='Y', max_length=1)),
                ('liquidity_rate', models.FloatField(null=True)),
                ('holders_share', models.FloatField(null=True)),
                ('holders_profit', models.FloatField(null=True)),
                ('holders_value', models.FloatField(null=True)),
                ('impairment_profit', models.FloatField(null=True)),
                ('issued_shares', models.FloatField(null=True)),
            ],
            options={
                'unique_together': {('valuation_date', 'code')},
            },
        ),
        migrations.CreateModel(
            name='FnGuideDailySnapShot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rpt_nm', models.TextField(default='')),
                ('rpt_tp', models.TextField(default='')),
                ('crp_cd', models.CharField(max_length=20)),
                ('crp_nm', models.TextField()),
                ('disc_date', models.DateField()),
                ('column_nm', models.CharField(max_length=100)),
                ('key', models.TextField(max_length=100)),
                ('value', models.FloatField(null=True)),
                ('value_rmk', models.TextField(null=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('id', 'rpt_nm', 'rpt_tp', 'crp_cd', 'disc_date', 'column_nm', 'key')},
                'index_together': {('rpt_nm', 'rpt_tp', 'crp_cd', 'disc_date', 'column_nm', 'key')},
            },
        ),
        migrations.CreateModel(
            name='EcosStatisticSearchData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STAT_CODE', models.CharField(max_length=20)),
                ('STAT_NAME', models.CharField(max_length=100)),
                ('ITEM_CODE1', models.CharField(max_length=20)),
                ('ITEM_NAME1', models.CharField(max_length=100)),
                ('ITEM_CODE2', models.CharField(max_length=20)),
                ('ITEM_NAME2', models.CharField(max_length=100)),
                ('ITEM_CODE3', models.CharField(max_length=20)),
                ('ITEM_NAME3', models.CharField(max_length=100)),
                ('UNIT_NAME', models.CharField(max_length=20)),
                ('TIME', models.CharField(max_length=20)),
                ('DATA_VALUE', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('STAT_CODE', 'ITEM_CODE1', 'ITEM_CODE2', 'ITEM_CODE3', 'UNIT_NAME', 'TIME')},
                'index_together': {('STAT_CODE', 'ITEM_CODE1', 'ITEM_CODE2', 'ITEM_CODE3', 'UNIT_NAME', 'TIME')},
            },
        ),
        migrations.CreateModel(
            name='EcosStatDetailItemList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('STAT_CODE', models.CharField(max_length=20)),
                ('STAT_NAME', models.CharField(max_length=100)),
                ('GRP_NAME', models.CharField(max_length=20)),
                ('ITEM_CODE', models.CharField(max_length=20)),
                ('ITEM_NAME', models.CharField(max_length=100)),
                ('CYCLE', models.CharField(max_length=20)),
                ('START_TIME', models.CharField(max_length=20)),
                ('END_TIME', models.CharField(max_length=20)),
                ('DATA_CNT', models.IntegerField()),
                ('CREATE_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('STAT_CODE', 'ITEM_CODE')},
                'index_together': {('STAT_CODE', 'ITEM_CODE')},
            },
        ),
        migrations.CreateModel(
            name='EcosServiceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('P_STAT_CODE', models.CharField(max_length=20)),
                ('STAT_CODE', models.CharField(max_length=20)),
                ('STAT_NAME', models.CharField(max_length=100)),
                ('CYCLE', models.CharField(max_length=20)),
                ('SRCH_YN', models.CharField(max_length=1)),
                ('ORG_NAME', models.CharField(max_length=100)),
                ('CREATE_AT', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('P_STAT_CODE', 'STAT_CODE')},
                'index_together': {('P_STAT_CODE', 'STAT_CODE')},
            },
        ),
    ]
